### PR TITLE
Update id.json

### PR DESCRIPTION
**Pull request by jiprastyo**
adding Indonesian translation for: https://dev-covid19-oita.netlify.app/ko/support/

## 📝 関連する issue / Related Issues
- #247 

## ⛏ 変更内容 / Details of Changes
- Indonesian translation for https://dev-covid19-oita.netlify.app/ko/support/

## 📸 スクリーンショット / Screenshots
oita covid

### CODE REVIEW

**Review by nojiri1098 — CHANGES_REQUESTED** [review]
thank you as always!
please adding a translation of "件"

image
image

**Comment by jiprastyo** [comment]
I looked for that specific part too but couldn't find it. 
could you please point out where exactly in the file?
thank you.

**Comment by nojiri1098** [comment]
it is solved 👍
you translated indices of "件", but that is not necessary.

**Review by nojiri1098 — APPROVED** [review]
thank you for adding 🙏

**Pull request merged**
